## Homework 5

#### Markdown Questions

- **Pandas** references both “Panel Data” and “Python Data Analysis”.
- The 2 collections in Pandas are *series* and *data frames*.
- Pandas can do *data cleansing*, *data normalization*, *merges and joins*, and *statistical analysis*.
- To permanently sort a DataFrame, the keyword *inplace* (set equal to *True*) should be used.
- A **CSV** (Comma Separated Values) file is a plain text file that stores data by delimiting data entries with commas.
- When cleaning data, we do not like *null* values.

#### Coding Exercise

In [26]:
# Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- .reshape()

import numpy as np

array = np.array([(1,2,3),(4,5,6),(7,8,9),(10,11,12)])
reshapedArray = array.reshape(2,3,2)
print(array)
print(reshapedArray)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [24]:
# Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20

sun = np.linspace(0,20,6)
print(sun)

[ 0.  4.  8. 12. 16. 20.]


In [25]:
# Make a Deep Copy of the above array

import copy

moon = copy.deepcopy(sun)
print(moon)

[ 0.  4.  8. 12. 16. 20.]


In [23]:
# Concatenate these 3 arrays into a new array named 'newArray'...

arrayA = ([[25, 16]])
arrayB = ([[11, 2], [13, 4]])
arrayC = ([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((arrayA,arrayB,arrayC))
print(newArray)

[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [22]:
# Sort 'newArray' in order into 'sortedArray'

sortedArray = np.sort(newArray)
print(sortedArray)

[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [6]:
# Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.

var1,var2,var3,var4 = array

print(var1)
print(var2)
print(var3)
print(var4)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [7]:
# Combined and sort the following arrays into one called 'comboArray' ...

one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.concatenate((one,two,three))
comboArray = np.sort(comboArray)
print(comboArray)

[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


In [8]:
# Take 'comboArray' and perform the following slicing activities:
# print sec1 - the 2nd element
# print sec2 - all elements from the 3rd element to the last
# print sec3 - all elements from the 4th to the 14th elements
# print sec4 - the last 6 elements
# print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
# print sec6 - from #20 every even element to the end
# print sec7 - from the last element moving forward, every 5th element.

print(comboArray[1])
print(comboArray[2:])
print(comboArray[3:14])
print(comboArray[-6:])
print(comboArray[-24:-10])
print(comboArray[-8::2])
print(comboArray[::-5])

1
[ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[ 3  4  5  6  7 10 11 12 13 14 15]
[22 23 24 25 26 27]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
[20 22 24 26]
[27 22 15 10  3]


In [18]:
# Using Series, create a DataFrame that looks like this:

import pandas as pd

ingredients = pd.Series(["Flour","Milk","Eggs","Spam"],name="Ingredients")
quantity = pd.Series([4,1,2,1],name="Quantity")
unit  = pd.Series(["cups","cup","large","can"],name="Unit")

index_labels = ["","","",""]
ingredients.index = index_labels
quantity.index = index_labels
unit.index = index_labels

df = pd.concat([ingredients,quantity,unit],axis=1)
print(df)

 Ingredients  Quantity   Unit
       Flour         4   cups
        Milk         1    cup
        Eggs         2  large
        Spam         1    can


In [15]:
# Take this data and create a DataFrame named studentData

dict = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
    }

studentData = pd.DataFrame(dict)
print(studentData)

      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket


In [17]:
# Add a new column to the DataFrame with the following deserts: ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

Desserts = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
studentData["Desserts"] = Desserts
print(studentData)

      Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

       Desserts  
0     ice cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Halwa  


In [21]:
# Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"

studentData.sort_values(by=["Name","address"],inplace=True)
print(studentData)

      Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

       Desserts  
3  Carrot Halwa  
2       waffels  
0     ice cream  
1  Cashew Fudge  


In [37]:
# Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:

df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])

df.to_csv("cows_and_goats.csv")
CaG = pd.read_csv("cows_and_goats.csv")
print(CaG)

  Unnamed: 0  Cows  Goats
0     Year 1    12     22
1     Year 2    20     19


In [36]:
# (A) Using Pandas, make your own .CSV file with data on vegetables and save it.
# (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.

vegetables = pd.DataFrame([["Lettuce","Leafy green"],["Potato","Root"],["Onion","Allium"],["Cabbage","Cruciferous"],["Pumpkin","Marrow"],["Celery","Edible plant stem"]],
                          columns=["Vegetable","Type"])

vegetables.to_csv("vegetables.csv",index=False)
df = pd.read_csv("vegetables.csv")
print(df)

print("\n")

df.sort_values(by="Type",inplace=True)
df.to_csv("sortedVegetables.csv",index=False)
dfS = pd.read_csv("sortedVegetables.csv")
print(dfS)

  Vegetable               Type
0   Lettuce        Leafy green
1    Potato               Root
2     Onion             Allium
3   Cabbage        Cruciferous
4   Pumpkin             Marrow
5    Celery  Edible plant stem


  Vegetable               Type
0     Onion             Allium
1   Cabbage        Cruciferous
2    Celery  Edible plant stem
3   Lettuce        Leafy green
4   Pumpkin             Marrow
5    Potato               Root
